kind: Service
apiVersion: v1
metadata:
  name: multicluster-global-hub-apiserver
  namespace: {{.Namespace}}
  annotations:
    "service.beta.openshift.io/serving-cert-secret-name": multicluster-global-hub-apiserver
spec:
  selector:
    app: multicluster-global-hub-apiserver
  ports:
    - name: secure
      protocol: TCP
      port: 443
      targetPort: 6443
---
apiVersion: v1
kind: Service
metadata:
  name: multicluster-global-hub-webhook
  namespace: {{.Namespace}}
  labels:
    name: multicluster-global-hub-webhook
    service: multicluster-global-hub-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-global-hub-webhook-certs
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
    name: webhook-server
  selector:
    app: multicluster-global-hub-apiserver