---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo
  labels:
    app: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operator
  template:
    metadata:
      labels:
        app: postgres-operator
    spec:
      containers:
      - name: operator
        image: postgres-operator
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: pgo
