resources:
- manager.yaml
- postgres/manager.yaml
- kafka

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
# - files:
#   - controller_manager_config.yaml
#   name: manager-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.3.3-0
- name: quay.io/stolostron/multicluster-global-hub-operator
  newName: quay.io/stolostron/multicluster-global-hub-operator
  newTag: latest
