apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kafka-operators
  namespace: multicluster-global-hub-kafka
spec:
  targetNamespaces:
    - multicluster-global-hub-kafka
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: multicluster-global-hub-kafka
spec:
  channel: strimzi-0.33.x
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
